# Generated by Django 4.1 on 2022-08-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rollnumber", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("marks", models.CharField(max_length=100)),
                ("grade", models.CharField(max_length=100)),
            ],
        ),
    ]
