# Generated by Django 4.1 on 2022-08-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="marks", new_name="mark",
        ),
    ]
