# Generated by Django 4.1 on 2022-08-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_marks_student_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="mark",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="rollnumber",
            field=models.CharField(default="", max_length=100),
        ),
    ]
