# Generated by Django 4.1 on 2022-09-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_student_age_student_email_student_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.CharField(default="", max_length=100)),
                ("rating", models.CharField(default="", max_length=100)),
            ],
            options={"unique_together": {("created_by", "rating")},},
        ),
        migrations.DeleteModel(name="Student",),
    ]
