# Generated by Django 4.1.3 on 2023-01-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uservote_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('rollno', models.CharField(default='', max_length=100)),
                ('marks', models.CharField(default='', max_length=100)),
                ('grade', models.CharField(default='', max_length=100)),
                ('age', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserVote',
        ),
    ]
