# Generated by Django 4.1.1 on 2022-09-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("email", models.CharField(default="", max_length=255)),
                ("city", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
