# Generated by Django 4.0.5 on 2022-07-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Super_AdminAccount',
        ),
    ]
