# Generated by Django 4.0.5 on 2022-07-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapi', '0002_delete_super_adminaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_AdminAcount',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(default='', max_length=255)),
                ('Lname', models.CharField(default='', max_length=255)),
                ('Email', models.EmailField(default='', max_length=255)),
                ('Username', models.CharField(default='', max_length=255)),
                ('Password', models.TextField(default='', max_length=255)),
                ('ContactNo', models.CharField(default='', max_length=100)),
                ('Role', models.CharField(choices=[('superadmin', 'superadmin'), ('subadmin', 'subadmin'), ('sumadmin', 'sumadmin'), ('submitadmin', 'submitadmin'), ('setadmin', 'setadmin')], default='subadmin', max_length=11)),
                ('Profile', models.ImageField(default='SuperAdmin/dummy.jpg', upload_to='SuperAdmin/')),
            ],
        ),
    ]
