# Generated by Django 4.1 on 2022-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(default="", max_length=255)),
                ("lastname", models.CharField(default="", max_length=255)),
                ("address", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(default="", max_length=255)),
                ("password", models.CharField(default="", max_length=255)),
                ("phone", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(default="", max_length=255)),
                ("lastname", models.CharField(default="", max_length=255)),
                ("address", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(default="", max_length=255)),
                ("password", models.CharField(default="", max_length=255)),
                ("phone", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
