# Generated by Django 4.1.5 on 2023-02-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooknotification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='webhooknotification',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webhooknotification',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
