# Generated by Django 4.1.5 on 2023-02-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_webhooknotification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooknotification',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
