# Generated by Django 4.1.7 on 2023-02-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_webhooknotification_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooknotification',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
