# Generated by Django 4.1.7 on 2023-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_webhooknotification_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='WebhookNotification',
        ),
    ]
