# Generated by Django 4.1.5 on 2023-03-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_third'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message_third',
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
