# Generated by Django 4.1.7 on 2023-03-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('phone', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.IntegerField(default='')),
            ],
        ),
    ]
