# Generated by Django 4.1.6 on 2023-02-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.CharField(default='', max_length=255)),
                ('user_2', models.CharField(default='', max_length=255)),
                ('amount', models.IntegerField(default='')),
            ],
        ),
    ]
