# Generated by Django 4.1 on 2022-08-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="email",),
        migrations.RemoveField(model_name="salary", name="amount",),
    ]
