# Generated by Django 4.1.3 on 2022-11-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True)),
                ("amaount", models.CharField(default="", max_length=255)),
                ("name", models.CharField(default="", max_length=255)),
                ("customer_id", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
