# Generated by Django 4.1.3 on 2022-11-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation", old_name="amaount", new_name="amount",
        ),
    ]
