# Generated by Django 4.1.3 on 2022-11-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0002_rename_amaount_reservation_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="amount",
            field=models.IntegerField(default="", max_length=255),
        ),
    ]
