# Generated by Django 4.1.3 on 2022-11-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0003_alter_reservation_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="date",
            field=models.DateField(verbose_name="%Y:%M:%D"),
        ),
    ]
