# Generated by Django 4.1.3 on 2023-01-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_address_student_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rollno',
        ),
    ]
