# Generated by Django 4.1.3 on 2022-11-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(default="", max_length=255)),
                ("lastname", models.CharField(default="", max_length=255)),
                ("address", models.CharField(default="", max_length=255)),
                ("email", models.EmailField(default="", max_length=255)),
                ("password", models.CharField(default="", max_length=255)),
                ("phone", models.CharField(default="", max_length=255)),
                ("state", models.CharField(default="", max_length=255)),
                ("city", models.CharField(default="", max_length=255)),
                ("country", models.CharField(default="", max_length=255)),
                ("zipcode", models.CharField(default="", max_length=255)),
                ("username", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("rollnumber", models.CharField(default="", max_length=100)),
                ("city", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
