# Generated by Django 4.1.3 on 2022-11-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_student_classid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="class", old_name="address", new_name="Class",
        ),
        migrations.RemoveField(model_name="class", name="city",),
        migrations.RemoveField(model_name="class", name="country",),
        migrations.RemoveField(model_name="class", name="email",),
        migrations.RemoveField(model_name="class", name="firstname",),
        migrations.RemoveField(model_name="class", name="lastname",),
        migrations.RemoveField(model_name="class", name="password",),
        migrations.RemoveField(model_name="class", name="phone",),
        migrations.RemoveField(model_name="class", name="state",),
        migrations.RemoveField(model_name="class", name="username",),
        migrations.RemoveField(model_name="class", name="zipcode",),
        migrations.RemoveField(model_name="student", name="city",),
        migrations.RemoveField(model_name="student", name="classid",),
        migrations.RemoveField(model_name="student", name="rollnumber",),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(default="", max_length=100),
        ),
    ]
