# Generated by Django 4.1.3 on 2022-11-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_address_class_class_remove_class_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="classid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.class",
            ),
        ),
    ]
