# Generated by Django 4.1.3 on 2022-11-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_student_classid"),
    ]

    operations = [
        migrations.RenameModel(old_name="Class", new_name="Class_name",),
    ]
